import type { WorldSpec } from "../engine/quest/WorldSpec";
import { ENGINE_VERSION, RUNTIME_VERSION, SPEC_VERSION } from "../engine/version/EngineVersion";

export const CyberRiskRoom: WorldSpec = {
  id: "cyber-risk-room",
  title: "Cyber Risk Room",
  description: "Inspect systems, find the exposure, and complete the incident triage.",
  version: SPEC_VERSION,
  specVersion: SPEC_VERSION,
  createdWithEngineVersion: ENGINE_VERSION,
  lastEditedWithEngineVersion: ENGINE_VERSION,
  requiredRuntimeVersion: RUNTIME_VERSION,
  requiredCapabilities: ["3d.primitives", "3d.picking", "materials.color", "materials.opacity"],
  preferredRenderer: "webgl2",
  allowRendererDegradation: true,
  metadata: { template: "CyberRiskRoom" },
  viewport: { width: 1280, height: 720, background: "#090d18" },
  environment: { background: "#090d18", ambientColor: "#dbeafe", showGrid: true, gridColor: "#263249" },
  camera: { position: [4.8, 3.6, 7.4], target: [0, 0.55, 0], fov: 44, near: 0.1, far: 100 },
  entities: [
    {
      id: "floor",
      name: "Incident Floor",
      type: "plane",
      transform: { position: [0, -0.55, 0], rotation: [0, 0, 0], scale: [7.5, 1, 5.2] },
      material: { color: "#111827", opacity: 1, roughness: 0.8 },
      geometry: {},
      visible: true,
      selectable: false,
      interactionIds: [],
    },
    {
      id: "server",
      name: "Public Server",
      type: "box",
      transform: { position: [-1.8, 0.35, 0], rotation: [0, -8, 0], scale: [0.8, 1.8, 0.75] },
      material: { color: "#38bdf8", opacity: 0.92, roughness: 0.45 },
      geometry: {},
      visible: true,
      selectable: true,
      interactionIds: ["scan-server"],
    },
    {
      id: "vault",
      name: "Data Vault",
      type: "cylinder",
      transform: { position: [1.6, 0.15, -0.6], rotation: [0, 0, 0], scale: [0.95, 1.45, 0.95] },
      material: { color: "#a78bfa", opacity: 0.95 },
      geometry: { segments: 32 },
      visible: true,
      selectable: true,
      interactionIds: ["inspect-vault"],
    },
    {
      id: "alert",
      name: "Threat Beacon",
      type: "sphere",
      transform: { position: [0.05, 1.35, 0.95], rotation: [0, 0, 0], scale: [0.55, 0.55, 0.55] },
      material: { color: "#f97316", opacity: 0.92, emissive: "#f97316" },
      geometry: { segments: 24, rings: 14 },
      visible: true,
      selectable: true,
      interactionIds: ["contain-alert"],
    },
  ],
  interactions: [
    {
      id: "intro",
      trigger: "sceneStart",
      conditions: [],
      actions: [{ type: "showMessage", title: "Briefing", message: "Click the server, vault, and beacon to resolve the triage path.", tone: "info" }],
    },
    {
      id: "scan-server",
      trigger: "click",
      targetEntityId: "server",
      conditions: [],
      actions: [
        { type: "setVariable", variable: "serverScanned", value: true },
        { type: "addScore", amount: 25 },
        { type: "showMessage", title: "Server scanned", message: "A public endpoint is exposing stale credentials.", tone: "warning" },
        { type: "highlightEntity", entityId: "server", color: "#7dd3fc" },
      ],
    },
    {
      id: "inspect-vault",
      trigger: "click",
      targetEntityId: "vault",
      conditions: [{ type: "variableEquals", variable: "serverScanned", value: true }],
      actions: [
        { type: "addScore", amount: 30 },
        { type: "gotoStage", stageId: "containment" },
        { type: "showMessage", title: "Vault protected", message: "The vault is isolated from the exposed endpoint.", tone: "success" },
      ],
    },
    {
      id: "contain-alert",
      trigger: "click",
      targetEntityId: "alert",
      conditions: [{ type: "stageIs", stageId: "containment" }],
      actions: [
        { type: "addScore", amount: 45 },
        { type: "hideEntity", entityId: "alert" },
        { type: "completeQuest", outcomeId: "contained" },
        { type: "showMessage", title: "Quest complete", message: "Incident contained. Export this quest as a standalone static package.", tone: "success" },
      ],
    },
  ],
  quest: {
    specVersion: SPEC_VERSION,
    variables: { serverScanned: false },
    score: 0,
    stages: [
      { id: "recon", title: "Recon", description: "Find the exposed system." },
      { id: "containment", title: "Containment", description: "Protect critical data and close the alert." },
    ],
    currentStage: "recon",
    outcomes: [{ id: "contained", title: "Contained", description: "The exposure was resolved.", minScore: 80 }],
    rules: [],
    completionConditions: [{ type: "scoreAtLeast", value: 80 }],
  },
  assets: [],
  exportSettings: {
    packageName: "cyber-risk-room",
    includeSourceSpec: true,
    minifyRuntime: false,
    defaultRenderer: "webgl2",
    includeCanvas2DFallback: true,
    includeStaticFallback: true,
    allowExperimentalWebGPU: false,
  },
};
