import type { WorldSpec } from "../engine/quest/WorldSpec";
import { ENGINE_VERSION, RUNTIME_VERSION, SPEC_VERSION } from "../engine/version/EngineVersion";

export const DecisionQuest3D: WorldSpec = {
  id: "decision-quest-3d",
  title: "Decision Quest 3D",
  description: "A lightweight branching decision room with outcome scoring.",
  version: SPEC_VERSION,
  specVersion: SPEC_VERSION,
  createdWithEngineVersion: ENGINE_VERSION,
  lastEditedWithEngineVersion: ENGINE_VERSION,
  requiredRuntimeVersion: RUNTIME_VERSION,
  requiredCapabilities: ["renderer:webgl2", "renderer:canvas2d", "export:single-html", "export:zip-static"],
  metadata: { template: "DecisionQuest3D" },
  viewport: { width: 1280, height: 720, background: "#101012" },
  environment: { background: "#101012", ambientColor: "#f1f5f9", showGrid: true, gridColor: "#30313a" },
  camera: { position: [4.5, 3.2, 6.8], target: [0, 0.25, 0], fov: 45, near: 0.1, far: 100 },
  entities: [
    {
      id: "path-a",
      name: "Fast Path",
      type: "box",
      transform: { position: [-1.35, 0.2, 0], rotation: [0, 18, 0], scale: [1.2, 0.85, 1.2] },
      material: { color: "#facc15", opacity: 0.94 },
      geometry: {},
      visible: true,
      selectable: true,
      interactionIds: ["choose-a"],
    },
    {
      id: "path-b",
      name: "Careful Path",
      type: "box",
      transform: { position: [1.35, 0.2, 0], rotation: [0, -18, 0], scale: [1.2, 0.85, 1.2] },
      material: { color: "#22c55e", opacity: 0.94 },
      geometry: {},
      visible: true,
      selectable: true,
      interactionIds: ["choose-b"],
    },
    {
      id: "outcome",
      name: "Outcome Marker",
      type: "sphere",
      transform: { position: [0, 1.3, -0.65], rotation: [0, 0, 0], scale: [0.48, 0.48, 0.48] },
      material: { color: "#94a3b8", opacity: 0.9 },
      geometry: { segments: 20, rings: 12 },
      visible: true,
      selectable: false,
      interactionIds: [],
    },
  ],
  interactions: [
    {
      id: "intro",
      trigger: "sceneStart",
      conditions: [],
      actions: [{ type: "showMessage", title: "Decision", message: "Choose a path. The export will preserve this logic without a backend.", tone: "info" }],
    },
    {
      id: "choose-a",
      trigger: "click",
      targetEntityId: "path-a",
      conditions: [],
      actions: [
        { type: "setVariable", variable: "choice", value: "fast" },
        { type: "addScore", amount: 45 },
        { type: "highlightEntity", entityId: "path-a", color: "#fde68a" },
        { type: "showMessage", title: "Fast path", message: "Speed improved, but resilience stayed moderate.", tone: "warning" },
      ],
    },
    {
      id: "choose-b",
      trigger: "click",
      targetEntityId: "path-b",
      conditions: [],
      actions: [
        { type: "setVariable", variable: "choice", value: "careful" },
        { type: "addScore", amount: 70 },
        { type: "highlightEntity", entityId: "outcome", color: "#86efac" },
        { type: "completeQuest", outcomeId: "resilient" },
        { type: "showMessage", title: "Careful path", message: "The team made the resilient decision.", tone: "success" },
      ],
    },
  ],
  quest: {
    specVersion: SPEC_VERSION,
    variables: { choice: "none" },
    score: 0,
    stages: [{ id: "choose", title: "Choose", description: "Select one path and review the outcome." }],
    currentStage: "choose",
    outcomes: [{ id: "resilient", title: "Resilient", description: "The careful path created the strongest outcome.", minScore: 70 }],
    rules: [],
    completionConditions: [{ type: "scoreAtLeast", value: 70 }],
  },
  assets: [],
  exportSettings: { packageName: "decision-quest-3d", includeSourceSpec: true, minifyRuntime: false },
};
