import type { WorldSpec } from "../engine/quest/WorldSpec";
import { ENGINE_VERSION, RUNTIME_VERSION, SPEC_VERSION } from "../engine/version/EngineVersion";

export const ProductConfiguratorLite: WorldSpec = {
  id: "product-configurator-lite",
  title: "Product Configurator Lite",
  description: "A compact 3D selection quest for product education and guided selling.",
  version: SPEC_VERSION,
  specVersion: SPEC_VERSION,
  createdWithEngineVersion: ENGINE_VERSION,
  lastEditedWithEngineVersion: ENGINE_VERSION,
  requiredRuntimeVersion: RUNTIME_VERSION,
  requiredCapabilities: ["3d.primitives", "3d.picking", "materials.color", "materials.opacity"],
  preferredRenderer: "webgl2",
  allowRendererDegradation: true,
  metadata: { template: "ProductConfiguratorLite" },
  viewport: { width: 1280, height: 720, background: "#0b0d10" },
  environment: { background: "#0b0d10", ambientColor: "#f8fafc", showGrid: true, gridColor: "#2f363d" },
  camera: { position: [4.2, 3.3, 6.2], target: [0, 0.45, 0], fov: 42, near: 0.1, far: 100 },
  entities: [
    {
      id: "base",
      name: "Core Module",
      type: "box",
      transform: { position: [0, 0.05, 0], rotation: [0, 22, 0], scale: [1.9, 0.85, 1.45] },
      material: { color: "#e5e7eb", opacity: 0.98 },
      geometry: {},
      visible: true,
      selectable: true,
      interactionIds: ["select-base"],
    },
    {
      id: "performance",
      name: "Performance Upgrade",
      type: "sphere",
      transform: { position: [-1.75, 1.0, -0.1], rotation: [0, 0, 0], scale: [0.55, 0.55, 0.55] },
      material: { color: "#34d399", opacity: 0.95 },
      geometry: { segments: 22, rings: 12 },
      visible: true,
      selectable: true,
      interactionIds: ["choose-performance"],
    },
    {
      id: "support",
      name: "Support Package",
      type: "cone",
      transform: { position: [1.8, 0.55, 0.25], rotation: [0, -12, 0], scale: [0.72, 1.1, 0.72] },
      material: { color: "#60a5fa", opacity: 0.95 },
      geometry: { segments: 28 },
      visible: true,
      selectable: true,
      interactionIds: ["choose-support"],
    },
  ],
  interactions: [
    {
      id: "intro",
      trigger: "sceneStart",
      conditions: [],
      actions: [{ type: "showMessage", title: "Configure", message: "Click modules to build a recommended product bundle.", tone: "info" }],
    },
    {
      id: "select-base",
      trigger: "click",
      targetEntityId: "base",
      conditions: [],
      actions: [
        { type: "setVariable", variable: "baseSelected", value: true },
        { type: "addScore", amount: 20 },
        { type: "showMessage", title: "Core selected", message: "The base module is ready for bundle choices.", tone: "success" },
      ],
    },
    {
      id: "choose-performance",
      trigger: "click",
      targetEntityId: "performance",
      conditions: [{ type: "variableEquals", variable: "baseSelected", value: true }],
      actions: [
        { type: "incrementVariable", variable: "addons", amount: 1 },
        { type: "addScore", amount: 35 },
        { type: "highlightEntity", entityId: "performance", color: "#86efac" },
        { type: "showMessage", title: "Performance added", message: "The bundle now supports heavier workloads.", tone: "success" },
      ],
    },
    {
      id: "choose-support",
      trigger: "click",
      targetEntityId: "support",
      conditions: [{ type: "variableEquals", variable: "baseSelected", value: true }],
      actions: [
        { type: "incrementVariable", variable: "addons", amount: 1 },
        { type: "addScore", amount: 35 },
        { type: "completeQuest", outcomeId: "recommended" },
        { type: "showMessage", title: "Bundle ready", message: "A customer-ready recommendation is complete.", tone: "success" },
      ],
    },
  ],
  quest: {
    specVersion: SPEC_VERSION,
    variables: { baseSelected: false, addons: 0 },
    score: 0,
    stages: [{ id: "configure", title: "Configure", description: "Select the base and recommended add-ons." }],
    currentStage: "configure",
    outcomes: [{ id: "recommended", title: "Recommended", description: "A complete bundle recommendation.", minScore: 70 }],
    rules: [],
    completionConditions: [{ type: "scoreAtLeast", value: 70 }],
  },
  assets: [],
  exportSettings: {
    packageName: "product-configurator-lite",
    includeSourceSpec: true,
    minifyRuntime: false,
    defaultRenderer: "webgl2",
    includeCanvas2DFallback: true,
    includeStaticFallback: true,
    allowExperimentalWebGPU: false,
  },
};
